### ISSUE TITLE
Poncelet not working in IE6

### ISSUE THREAD

**Issue by nolaneo** [ocfnash/poncelet#1]
My users from the 90's need to access their Poncelets but this application will not boot.
Please note that the standard resolution is `320x240`. Please fix.

**Comment by mckenna** [comment]
Can confirm this doesn't work in IE6. Pretty raging to be honest.

![screen shot 2018-06-21 at 13 59 50](https://user-images.githubusercontent.com/26238/41720607-83abadc2-755b-11e8-9b5c-68894587f318.png)
