### ISSUE TITLE
[Suggestion] Rename Poncelet to Boncelet

### ISSUE THREAD

**Issue by nolaneo** [ocfnash/poncelet#2]
Ponce has an [undesirable meaning](https://en.wiktionary.org/wiki/ponce) in English. I suggest we rename this project to Boncelet as to not offend anyone.

Bonce has the whimsical meaning of "[a persons head](https://en.oxforddictionaries.com/definition/bonce)" which I think fits well with the ethos of this repo.

Boncelet is also a family name (which IMO Jean-Victor Poncelet should have considered renaming to in the 18th century) keeping with the family name theme of the current naming.

cc @mckenna for thoughts.

**Comment by mckenna** [comment]
I would have to strongly agree here. As we all know, Jean Victor Poncelet is an anagram for Novel Catnip Ejector. Naturally, this would be quite enticing to the feline population, but, again, as we all know, cats _cannot_ be trusted. 

I personally find a Vertical Neon Object far more appealing, and as it happens, this is an anagram for Jean Victor _Boncelet_. I am assuming the vertical neon object in question here is a very large neon sign advertising your blog that will be affixed to the front of your home.

**Comment by nolaneo** [comment]
As far as I'm aware, @ocfnash's house is stored in Amazon Glacier. I'm not sure their residents committee will allow any neon signs, however I do agree with the Vertical Neon Object naming regardless.

@michellefitz can you give your thoughts on the point that _cats cannot be trusted_. I feel you may have some good insight here.

**Comment by ocfnash** [comment]
Thanks guys, these are top notch suggestions. I've added an item to Asana, several cards to Trello, and a list of checkboxes to TickTick to make sure I get round to all these excellent ideas.

Disappointed @michellefitz couldn't be bothered to chip in 😿
